git:
  commitMessage: "[chore] Release v${version}"
  requireBranch: main
github:
  release: true
  web: true
  releaseName: "${version}: "
npm:
  publish: true
hooks:
  before:init:
    - make test
    - make build
  after:bump:
    - npm i
    - git add package-lock.json
  after:release: "echo Successfully released ${name} v${version} to ${repo.repository} and NPM."
